### ISSUE TITLE
Readability issues due to improper scaling of content in the app.

### ISSUE THREAD

**Issue by jatinAroraGit** [ImmutableBox/whiteboard#1]
Hey there,
The issue is related to accessibility and readability of the app when used on phones having dimensions less than 375px x 433px.
Cause : Improper scaling on small screen devices.
Effects: Cannot read the contents of the note in the div. Have to zoom in and out repeatedly hence causing readability issues.

I would like to work on this.
Have a good day.

**Comment by Immutablevoid** [comment]
Thanks for finding this bug @jatinAroraGit . I will assign this bug to you to work on.

**Comment by Immutablevoid** [comment]
This issue has been fixed via 272d8d5 and is now on the master branch.
